// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoloKnights.Data;

#nullable disable

namespace SoloKnights.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304165422_CreatedModels")]
    partial class CreatedModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoloKnights.Models.MainModels.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiomeId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BiomeId");

                    b.HasIndex("FloorId");

                    b.ToTable("Boss");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Buff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buff");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("CritChance")
                        .HasColumnType("int");

                    b.Property<int>("Dmg")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassiveId")
                        .HasColumnType("int");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PassiveId");

                    b.HasIndex("PriceId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("LevelId");

                    b.ToTable("Enemy");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lobby");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CritChance")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Dmg")
                        .HasColumnType("int");

                    b.Property<int>("EnergyCost")
                        .HasColumnType("int");

                    b.Property<int>("Inaccuracy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RarityId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RarityId");

                    b.ToTable("Weapon");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Weapon");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Biome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Biome");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkill");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.GameObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("GameObject");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Number")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.NPC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("NPC");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rarity");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Skin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("PriceId");

                    b.ToTable("Skin");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.StarterWeapon", b =>
                {
                    b.HasBaseType("SoloKnights.Models.MainModels.Weapon");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasFilter("[CharacterId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("StarterWeapon");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Boss", b =>
                {
                    b.HasOne("SoloKnights.Models.SupModels.Biome", "Biome")
                        .WithMany("Bosses")
                        .HasForeignKey("BiomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoloKnights.Models.SupModels.Floor", null)
                        .WithMany("Bosses")
                        .HasForeignKey("FloorId");

                    b.Navigation("Biome");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Character", b =>
                {
                    b.HasOne("SoloKnights.Models.MainModels.Buff", "Passive")
                        .WithMany()
                        .HasForeignKey("PassiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoloKnights.Models.SupModels.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passive");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Enemy", b =>
                {
                    b.HasOne("SoloKnights.Models.SupModels.Floor", null)
                        .WithMany("Enemies")
                        .HasForeignKey("FloorId");

                    b.HasOne("SoloKnights.Models.SupModels.Level", "Level")
                        .WithMany("Enemies")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Weapon", b =>
                {
                    b.HasOne("SoloKnights.Models.SupModels.Rarity", "Rarity")
                        .WithMany("Weapons")
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Biome", b =>
                {
                    b.HasOne("SoloKnights.Models.SupModels.Floor", "Floor")
                        .WithMany("Biomes")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.CharacterSkill", b =>
                {
                    b.HasOne("SoloKnights.Models.MainModels.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.GameObject", b =>
                {
                    b.HasOne("SoloKnights.Models.MainModels.Lobby", "Lobby")
                        .WithMany("Objects")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Level", b =>
                {
                    b.HasOne("SoloKnights.Models.SupModels.Floor", "Floor")
                        .WithMany("Levels")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.NPC", b =>
                {
                    b.HasOne("SoloKnights.Models.MainModels.Lobby", "Lobby")
                        .WithMany("NPCs")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Skin", b =>
                {
                    b.HasOne("SoloKnights.Models.MainModels.Character", "Character")
                        .WithMany("Skins")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloKnights.Models.SupModels.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.StarterWeapon", b =>
                {
                    b.HasOne("SoloKnights.Models.MainModels.Character", "Character")
                        .WithOne("StarterWeapon")
                        .HasForeignKey("SoloKnights.Models.SupModels.StarterWeapon", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Character", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Skins");

                    b.Navigation("StarterWeapon")
                        .IsRequired();
                });

            modelBuilder.Entity("SoloKnights.Models.MainModels.Lobby", b =>
                {
                    b.Navigation("NPCs");

                    b.Navigation("Objects");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Biome", b =>
                {
                    b.Navigation("Bosses");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Floor", b =>
                {
                    b.Navigation("Biomes");

                    b.Navigation("Bosses");

                    b.Navigation("Enemies");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Level", b =>
                {
                    b.Navigation("Enemies");
                });

            modelBuilder.Entity("SoloKnights.Models.SupModels.Rarity", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
